### ISSUE TITLE
entity view

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#3]
When viewing an entity, all statements explicitly made about that entity shall be viewable

http://test.wmocodes.info/grib2/codeflag/4.2/0-0-13
shall provide the information in the way that
http://codes.wmo.int/grib2/codeflag/4.2/0-0-13
does in its properties tab

**Comment by der** [comment]
This seems to be a configuration issue that is baked into the wmo triple store snapshot.

The default rendering checks the type of the item to render against the entries in /system/typed-templates.

The triple store image contents include an entry in that table which matches skos:Concepts and renders them via the concept-render.vm template which only shows definition and core SKOS properties instead of the generic property table. Many (thought not all) of the entries in the WMO codes registry are skos:Concepts and so trigger this rendering. Deleting the Concept entry from  /system/typed-templates in a local image restores normal property table rendering.

The boot directory doesn't seem to contain this  /system/typed-templates entry so can only assume it is created as part of the content bootstrap process. Suggest just removing it.

I've added the option to suppress the cross-links display (since I think you aren't using them) which allows the property table to span the width of the page, which makes it more readable.

**Comment by marqh** [comment]
Hi @der 

just to be clear, are you suggesting that the entity
 http://codes.wmo.int/system/typed-templates/concept
 was added at an earlier point and is now causing this rendering limitation; 
 we're not sure why this is needed so it's likely best to just remove it?

i think this dates back to a previous iteration of a concept-render.vm template from an old version

**Comment by der** [comment]
Hi @marqh 

Yes exactly. 

I can believe it derives from an earlier iteration of registry-config-base/registry-deploy-poc. Since it doesn't seem be in the boot area (unless I'm missing something) then it'll only get into a clean rebuild of the registry state if it is being added via your API initialization script.

**Comment by marqh** [comment]
fixed and tested on 
test.wmocodes.info
